#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-sphinxcontrib_bibtex
Version  : 2.4.2
Release  : 28
URL      : https://files.pythonhosted.org/packages/40/17/8349d5dd28d71d2a25c7a6f317071b9360aefc3090a2abd475c8a5937811/sphinxcontrib-bibtex-2.4.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/40/17/8349d5dd28d71d2a25c7a6f317071b9360aefc3090a2abd475c8a5937811/sphinxcontrib-bibtex-2.4.2.tar.gz
Summary  : Sphinx extension for BibTeX style citations.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-sphinxcontrib_bibtex-license = %{version}-%{release}
Requires: pypi-sphinxcontrib_bibtex-python = %{version}-%{release}
Requires: pypi-sphinxcontrib_bibtex-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(docutils)
BuildRequires : pypi(pybtex)
BuildRequires : pypi(pybtex_docutils)
BuildRequires : pypi(sphinx)

%description
sphinxcontrib-bibtex
====================
|ci| |codecov| |version| |license|
Sphinx extension for BibTeX style citations.

%package license
Summary: license components for the pypi-sphinxcontrib_bibtex package.
Group: Default

%description license
license components for the pypi-sphinxcontrib_bibtex package.


%package python
Summary: python components for the pypi-sphinxcontrib_bibtex package.
Group: Default
Requires: pypi-sphinxcontrib_bibtex-python3 = %{version}-%{release}

%description python
python components for the pypi-sphinxcontrib_bibtex package.


%package python3
Summary: python3 components for the pypi-sphinxcontrib_bibtex package.
Group: Default
Requires: python3-core
Provides: pypi(sphinxcontrib_bibtex)
Requires: pypi(docutils)
Requires: pypi(pybtex)
Requires: pypi(pybtex_docutils)
Requires: pypi(sphinx)

%description python3
python3 components for the pypi-sphinxcontrib_bibtex package.


%prep
%setup -q -n sphinxcontrib-bibtex-2.4.2
cd %{_builddir}/sphinxcontrib-bibtex-2.4.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649690722
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-sphinxcontrib_bibtex
cp %{_builddir}/sphinxcontrib-bibtex-2.4.2/LICENSE.rst %{buildroot}/usr/share/package-licenses/pypi-sphinxcontrib_bibtex/3c6a5c0c3479b7bf6f34159ff2310936389af1bb
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-sphinxcontrib_bibtex/3c6a5c0c3479b7bf6f34159ff2310936389af1bb

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
