#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sphinxcontrib-bibtex
Version  : 0.4.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/97/a7/564e1949e3a471f88947baf5c3ac08248a43609e6da6544470877b7e2102/sphinxcontrib-bibtex-0.4.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/97/a7/564e1949e3a471f88947baf5c3ac08248a43609e6da6544470877b7e2102/sphinxcontrib-bibtex-0.4.1.tar.gz
Summary  : A Sphinx extension for BibTeX style citations.
Group    : Development/Tools
License  : BSD-2-Clause
Requires: sphinxcontrib-bibtex-license = %{version}-%{release}
Requires: sphinxcontrib-bibtex-python = %{version}-%{release}
Requires: sphinxcontrib-bibtex-python3 = %{version}-%{release}
Requires: Sphinx
Requires: six
BuildRequires : buildreq-distutils3

%description
citations to be inserted into documentation generated by

%package license
Summary: license components for the sphinxcontrib-bibtex package.
Group: Default

%description license
license components for the sphinxcontrib-bibtex package.


%package python
Summary: python components for the sphinxcontrib-bibtex package.
Group: Default
Requires: sphinxcontrib-bibtex-python3 = %{version}-%{release}

%description python
python components for the sphinxcontrib-bibtex package.


%package python3
Summary: python3 components for the sphinxcontrib-bibtex package.
Group: Default
Requires: python3-core

%description python3
python3 components for the sphinxcontrib-bibtex package.


%prep
%setup -q -n sphinxcontrib-bibtex-0.4.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1545315862
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/sphinxcontrib-bibtex
cp LICENSE.rst %{buildroot}/usr/share/package-licenses/sphinxcontrib-bibtex/LICENSE.rst
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sphinxcontrib-bibtex/LICENSE.rst

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
